### ISSUE TITLE
Current plug-in incompatible with 2016.1.2 RC2

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#20]
Probably not very important but thought I'd mention it:

![image](https://cloud.githubusercontent.com/assets/92322/15048889/f09dd1a4-1297-11e6-955e-0a60ba849783.png)

/cc @dmitry-zhuravlev

**Comment by dmitry-zhuravlev** [comment]
Yeach, I added restriction to the latest release version because you told me that there is some problems while try to sync project in EAP build...  Not tested EAP yet. Maybe it will be more reasonable to test it against 2016.1.2 after general availability, just to eliminate possible changing in API which usually take place in EAP very often.

**Comment by cbeust** [comment]
The problems I reported were entirely my fault (I was using an old Intellij
SDK to run the plug-in), so you can discard my observation. Feel free to
remove the restrictions.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
Checked on 145.970 and it works.
Removed upper bound in 53b897a
