### ISSUE TITLE
Current implementation no longer uses the libraries

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#21]
I notice that the Libraries created by the plug-in are no longer used:

![image](https://cloud.githubusercontent.com/assets/92322/15051701/6b46ceca-12a6-11e6-815b-31a1805bb26c.png)

and instead, these dependencies are added directly to each module:

![image](https://cloud.githubusercontent.com/assets/92322/15051707/75f5dc94-12a6-11e6-9694-5d5ec9bad178.png)

Was that intentional? I'm fine with that approach but I thought creating libraries was a bit cleaner.

If we really don't need that code any more, we can remove it.

**Comment by dmitry-zhuravlev** [comment]
At the moment IDEA handle all lifecycle of library create\attach\dispose together with module. So there is no need to do it manually. Hence Dependencies.kt not needed any more. I'll delete it.

Also there is more convinient to see in the module exact dependencies which module have and not dependencies grouped by scope. Because you can quickly navigate to particular jar from "Project view" and from module dependencies view (and don't need to open another window with library content and search jar there). Also you see which exactly library(groupId:artifactId:version) in the name is used - this information is lost while grouping by scope because some library can have jar which named differs from groupId:artifactId:version.
Thats why Gradle and Maven plugins have the same library handling.

**Comment by cbeust** [comment]
Understood, thanks for the clarifications! Feel free to delete the old
files whenever convenient.

## 

Cédric
