### ISSUE TITLE
The plug-in doesn't seem to launch its server properly

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#26]
Trying to import aproject or sync a build file when no server is running results in an error.

However, if I launch a server manually, both imports and syncs work fine (@kmruiz saw the same thing).

It looks like the plug-in is not launching its own server correctly.

/cc @kmruiz

![image](https://cloud.githubusercontent.com/assets/92322/15086263/fb97ee7e-138b-11e6-9bc7-1a993cb0aba3.png)

**Comment by dmitry-zhuravlev** [comment]
Just to check some assumption, try the following:
1) Close all instances of IDEA and execute in shell: `lsof -i 4tcp:1246 -sTCP:LISTEN`
2) Kill founded process by executing: `kill -9 <PID>` where <PID> is the pid of founded process
3) Launch IDEA with plugin and press refresh button in Kobalt's tool window

It seems that this workflow helps me to overcome mentioned problem.
The assumption is that there is already launched server with some old version of Kobalt which produce this error. At the moment plugin does't properly shutdown server, so socket becomes opened even if IDEA with plugin closed. Maybe we should think about some shutdown hook like `getDependencies()` command which can gracefully shutdown server after reimport completes.

**Comment by dmitry-zhuravlev** [comment]
Indeed, 500 server error produced in cases of already started server. Can be reproduced as following:
1) Run "refresh" on some Kobalt project
2) After successfull "refresh" execute GET request with `buildFile` param which is differ from `Build.kt` located in refreshed project and you got 500 error.

@cbeust In general this means that server does't support several Build.kt files (from different places) at the same time. This should be changed in order to support multiple projects opened in several IDEA instances.

**Comment by cbeust** [comment]
Yes, I've been improving this part to be reentrant (allowing multiple
builds at the same time) but not quite there yet.

I'll fix it eventually but I don't think it's the most important thing
right now, since simultaneous builds should be rare. Let's just make sure
that for single builds, the plug-in + server interaction is rock solid.

## 

Cédric

**Comment by kmruiz** [comment]
I usually have the kobalt project, my plugin and a sample project open so it's annoying because all of them use kobalt for building themselves. But I agree with @cbeust that probably the priority is to work without problems with only one project, because it's the common case.

@dmitry-zhuravlev Could be possible for the plugin to negotiate with Kobalt in which port the server is going to listen? Would be easier to support multiple projects and also makes things cleaner and easier. Having a server for multiple projects could make things hard for project-scoped actions, like caching or updating IMHO.

**Comment by dmitry-zhuravlev** [comment]
Currently port for server start obtained from properties which located in home directory. So in theory it is posible to implement server start with port passed with parameter. But I think that launching each time a new server instance for each oppened in IDEA project not a good way since will lead to open unnecessary java processes which already more than one (server process+IDEA external api process) So reentrant server is a good approach I think. Evaluation of different Build.kt files should be independent by design, so there is no problen with project-scoped actions. And I agree that this is not the prio one thing to implement and we should just to keep in mind this feature for further development.

**Comment by dmitry-zhuravlev** [comment]
Looks like obsolete issue.
