### ISSUE TITLE
Synchronizing should not alter the module's output path

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#47]
Every time I sync, my module's output directory gets changed to "module compile output path":

![image](https://cloud.githubusercontent.com/assets/92322/16281986/433e46a4-3873-11e6-8685-025af9f27519.png)

while they were initially at "inherit":

![image](https://cloud.githubusercontent.com/assets/92322/16282008/58d0d70c-3873-11e6-8d6a-03865daa1dc3.png)

I think synchronization should not alter this setting.

**Comment by dmitry-zhuravlev** [comment]
Compiler output path should be set to `{PROJECT_DIR}/kobaltBuild/classes` for compile scope and `{PROJECT_DIR}/kobaltBuild/test-classes` this brings possibility to IDEA reuse already compiled by Kobalt classes. 

`Inherit project compile output path` this is wrong choose because IDEA will compile it to something like `{PROJECT_ROOT}/out` This will lead to duplicate compiled classes with IDEA and Kobalt and every time when user wants to start something in IDEA he will wait until IDEA compile classes again even if this classes was compiled previously by Kobalt.

Thats why plugin track and set the right compile out on every sync.

**Comment by cbeust** [comment]
I see. This makes sense but it's still a bit painful on my side. I'll see what I can do to adjust.

Thanks.
