### ISSUE TITLE
Can't see the tasks

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#50]
I was checking to see if the new tasks (`checkVersions` and `update`) appear in the window but I can't see any task at all with the current plug-in (the one in master, not the published one):

![image](https://cloud.githubusercontent.com/assets/92322/16397346/5d220924-3c70-11e6-9f60-4284fc149367.png)

**Comment by cbeust** [comment]
ping @dmitry-zhuravlev 

Any update? This is the only thing keeping me from releasing the new plug-in...

**Comment by dmitry-zhuravlev** [comment]
Sorry for delay, I was busy on my regular job...

I guess it is because Kobalt doesn't send it with response. Just tested with server instance launched with `com.beust.kobalt.MainKt` and client `com.beust.kobalt.app.remote.KobaltClient.kt` (without IDEA plugin)

Here is what I got:

![screen shot 2016-06-29 at 20 23 07](https://cloud.githubusercontent.com/assets/6297697/16461869/bbf419ee-3e3f-11e6-862b-5d7d155846bf.png)

**Comment by cbeust** [comment]
Ok will take a look, thanks!

## 

Cédric

**Comment by cbeust** [comment]
You were right, it was a bug in Kobalt. Fixed in master. Sorry for the false alarm!

**Comment by cbeust** [comment]
And they're back, including the new ones `update` and `checkVersions`:
- @pabl0rg

![image](https://cloud.githubusercontent.com/assets/92322/16463722/8871618c-3de3-11e6-85bf-8ef6802d920f.png)

**Comment by dmitry-zhuravlev** [comment]
Sounds good! ;)

**Comment by cbeust** [comment]
New plug-in released.
