### ISSUE TITLE
Loading plugins() disables IDEA plug-in

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt-intellij-plugin#56]
I created a project with `./kobaltw --init java`, added the following to the `Build.kt` file:

``` kotlin
import com.beust.kobalt.plugins

val pl = plugins("net.thauvin.erik:kobalt-exec:0.6.2")
```

Imported as a Kobalt project into IDEA 2016.2 (Windows), the IDEA plugin is basically disabled:

![capture](https://cloud.githubusercontent.com/assets/705618/17376046/9b01d35e-5968-11e6-92d8-174d7dd6ca3d.PNG)

I then commented the `plugins()` line out and reloaded:

![capture2](https://cloud.githubusercontent.com/assets/705618/17376097/d2c43886-5968-11e6-9a3b-500ec7aaf0be.PNG)

Works.

Additionally, I have never been able to import a Kobalt project as an `.ipr`, only `.iml` seems to work.

**Comment by cbeust** [comment]
Mmmh that's mysterious. @dmitry-zhuravlev any thoughts?

**Comment by dmitry-zhuravlev** [comment]
"the IDEA plugin is basically disabled" I think you mean that tool window doesn't show anything? If so I suppose that Kobalt return nothing because of 
`val pl = plugins("net.thauvin.erik:kobalt-exec:0.6.2")` for some reason...

"Additionally, I have never been able to import a Kobalt project as an .ipr, only .iml seems to work." 
".ipr" it is a legacy IDEA project format
".iml" it is a IDEA module format.
Maybe you mean "...as an .ipr, only .idea seems to work" you cannot compare .ipr with .iml because it is a different things.
Anyway I haven't check plugin with legacy .ipr based version of project. If you have some test .ipr based projects you are welcome to show me the concrete example.

**Comment by ethauvin** [comment]
> "the IDEA plugin is basically disabled" I think you mean that tool window doesn't show anything? If so I suppose that Kobalt return nothing because of 
> val pl = plugins("net.thauvin.erik:kobalt-exec:0.6.2") for some reason...

Actually, it'll ultimately give you a warning saying the module is no longer a valid Kobalt module and the Kobalt tool window will completely disappear, and to be clear, it doesn't matter which plugin is used, even @cbeust `kobalt-line-count` will fail.

> Anyway I haven't check plugin with legacy .ipr based version of project. If you have some test .ipr based projects you are welcome to show me the concrete example.

`./kobaltw --init java` then import as `.ipr`.

**Comment by dmitry-zhuravlev** [comment]
Tried with: 
`import com.beust.kobalt.plugins
val pl = plugins("net.thauvin.erik:kobalt-exec:0.6.2")`

And after some improvement in the plugin's output I see some exceptions which was thrown inside Kobalt:

`Caused by: java.lang.AssertionError: com.beust.kobalt.KobaltException: Couldn't create PluginInfo: net.thauvin.erik.kobalt.plugin.exec.ExecPlugin`

@cbeust any thoughts about it?

**Comment by dmitry-zhuravlev** [comment]
> ./kobaltw --init java then import as .ipr.

Tried to do it and it works for me without any problem:

![image](https://cloud.githubusercontent.com/assets/6297697/17481774/67263232-5d87-11e6-91d8-231b93ef2c62.png)

**Comment by ethauvin** [comment]
> Tried to do it and it works for me without any problem:

It worked for me today too. Whatever @cbeust changed fixed it.
