### ISSUE TITLE
"Configure with Kobalt" doesn't do anything

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#81]
I see two issues with this action:

- After running it, I still see the "Kotlin not configured" warning
- It adds the `kotlin-test` dependency even if it's already there:

![image](https://cloud.githubusercontent.com/assets/92322/26118290/350af62e-3a1e-11e7-9e91-b25895f7eb7a.png)

**Comment by dmitry-zhuravlev** [comment]
>After running it, I still see the "Kotlin not configured" warning

Modification of `Build.kt` doesn't lead to project re-import  unless "Auto-import" option explicitly specified:
 
![image](https://cloud.githubusercontent.com/assets/6297697/26153508/52803218-3b14-11e7-9fbb-18ab3b4f5aae.png)

>It adds the kotlin-test dependency even if it's already there

It is a known issue at the moment. 
Anyway not a big deal since if Kobalt server will send Kotlin libs to plugin "Configure with Kobalt" will not need anymore. (see https://github.com/cbeust/kobalt/issues/406)

**Comment by dmitry-zhuravlev** [comment]
Also I think that I need to remove `kotlin-test` dependency configuration because it is optional and not really a part of Kotlin runtime.
